name: 该倒灶了
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: '“有时间就要学习。”——理塘丁真.'
company: Tuyoshi kogyo♂ 津吉工業♂  # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: Los Santos # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: sillybfaq@163.com
  github: https://ichuan236.github.io/test/
  #twitter: razonyang
  #patreon: razonyang
  #paypal: razonyang
  rss: "" # Remove RSS
